import { test, expect } from '@playwright/test';

test('Auth - User Registration', async ({ page }) => {
  await page.goto('./');
  await page.getByRole('button', { name: 'Register' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('Lakshani Jananjalee');
  await page.getByRole('textbox', { name: 'Select Date of Birth' }).click();
  await page.getByText('2026', { exact: true }).click();
  await page.getByRole('option', { name: '2006' }).click();
  await page.getByText('July').click();
  await page.getByRole('option', { name: 'June' }).click();
  await page.getByText('19').click();
  await page.getByRole('combobox', { name: 'Select Gender' }).click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.getByRole('button', { name: 'Next Step' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number' }).fill('703889278');
  await page.getByRole('combobox', { name: 'Select Province', exact: true }).click();
  await page.getByRole('option', { name: 'North-Western (වයඹ)' }).click();
  await page.getByRole('combobox', { name: 'Select District' }).click();
  await page.getByRole('option', { name: 'Kurunegala (කුරුණෑගල)' }).click();
  await page.getByRole('button', { name: 'Next Step' }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password', exact: true }).fill('123456');
  await page.getByRole('textbox', { name: 'Confirm Password' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password' }).fill('123456');
  await page.getByRole('checkbox', { name: 'I agree to the Terms &' }).check();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('#otp-login-0').fill('3');
  await page.locator('#otp-login-1').fill('5');
  await page.locator('#otp-login-2').fill('8');
  await page.locator('#otp-login-3').fill('6');
  await page.locator('#otp-login-4').fill('2');
  await page.locator('#otp-login-5').fill('8');
  await page.locator('#otp-login-5').press('Enter');
  await page.getByRole('button', { name: 'Verify & Login' }).click();
});